// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Class struct {
	ID        uuid.UUID
	Name      string
	CourseID  uuid.UUID
	Lecture   string
	TimeStart time.Time
	TimeEnd   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Course struct {
	ID        uuid.UUID
	Name      string
	Sks       int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Role struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	Major          string
	Faculty        string
	TotalSks       sql.NullInt32
	RoleID         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
