// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID           pgtype.UUID
	Name         string
	CodeClass    string
	TotalStudent pgtype.Int4
	Lecturer     string
	CourseID     pgtype.UUID
	TimeStart    pgtype.Time
	TimeEnd      pgtype.Time
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Course struct {
	ID        pgtype.UUID
	Name      string
	Sks       int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Role struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
	FullName       string
	Nim            string
	Major          string
	Faculty        string
	TotalSks       pgtype.Int4
	Semester       int32
	Contact        string
	RoleID         string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type UserClass struct {
	ID        int32
	UserID    pgtype.UUID
	ClassID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
