// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: student.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    email,
    hashed_password,
    full_name,
    nim,
    major,
    faculty,
    semester,
    contact,
    role_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id
`

type InsertUserParams struct {
	Email          string
	HashedPassword string
	FullName       string
	Nim            string
	Major          string
	Faculty        string
	Semester       int32
	Contact        string
	RoleID         string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.HashedPassword,
		arg.FullName,
		arg.Nim,
		arg.Major,
		arg.Faculty,
		arg.Semester,
		arg.Contact,
		arg.RoleID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
