CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() ,
  email VARCHAR(255) NOT NULL UNIQUE ,
  hashed_password VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  nim VARCHAR(15) NOT NULL UNIQUE ,
  major VARCHAR(255) NOT NULL,
  faculty VARCHAR(36) NOT NULL,
  total_sks INT,
  semester INT NOT NULL,
  contact VARCHAR(13) NOT NULL,
  role_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);